Repository edm00se/awesome-board-games, pull requests merged in 2023-10, with the labels that each got.

#292 Add The Quacks of Quedlinburg
  readme.md
Labels: needs work

#293 Add The Quest for El Dorado
  readme.md
Labels: needs work

#395 Added Dice Forge
  readme.md
Labels: needs work

#392 Added Verdant
  readme.md
Labels: needs work

#382 Added Space Marine The Board Game
  readme.md
Labels: needs work

#398 Added Kemet
  readme.md
Labels: needs work

#399 Add Photosynthesis
  readme.md
Labels: needs work

#412 Added Amerigo game
  readme.md
Labels: needs work

#411 Added Diplomacy Game
  readme.md
Labels: needs work

#413 Added Lords of Vegas
  readme.md
Labels: needs work

#414 Added Zombie Kidz Evolution
  readme.md
Labels: needs work

#416 Added Arkham Horror game
  readme.md
Labels: needs work

#418 Added Caylus | MultiPlayer Game
  readme.md
Labels: needs work

#417 five tribes
  readme.md
Labels: needs work

#445 Adds Star Wars: The Deckbuilding Game
  readme.md
Labels: needs work

#438 Added game - Shadow of Brimstone.
  readme.md
Labels: needs work, pending

#362 Added Ashtapada
  readme.md
Labels: hacktoberfest-accepted, ancient

#448 Added new game Chaupar
  readme.md
Labels: review in progress

#453 Added The Gilded Realms
  readme.md
Labels: needs work
